/**
 * docs.ts — linklab docs [alias]
 *
 * Génère la documentation Markdown depuis {alias}.json :
 *   linklab/docs/entities.md   — entités + colonnes
 *   linklab/docs/routes.md     — physical + semantic + composed + virtual
 *   linklab/docs/use-cases.md  — use cases métier
 */

import * as fs from 'fs'
import * as path from 'path'
import chalk from 'chalk'
import { loadConfig, resolveAlias } from '../config.js'

export async function docs(options: { alias?: string } = {}): Promise<void> {
  const cwd = process.cwd()

  let alias: string
  let outDir: string
  let config: any

  try {
    const resolved = resolveAlias(cwd, options.alias)
    alias = resolved ?? path.basename(cwd)
    ;({ config, outDir } = await loadConfig(cwd, alias))
  } catch (e) {
    console.error(`\n  ✖  ${(e as Error).message}\n`)
    process.exit(1)
  }

  const docsDir = path.resolve(cwd, config?.output?.dir ?? `./linklab/${alias}`, '..', 'docs')
  const compiledPath = path.join(outDir, `${alias}.json`)
  const schemaPath = path.join(outDir, '.linklab', `${alias}.analyzed-schema.gen.json`)
  const dictPath = path.join(outDir, `${alias}.dictionary.gen.json`)
  const ucGenPath = path.join(outDir, `${alias}.use-cases.gen.json`)
  const ucOverride = path.join(outDir, `${alias}.use-cases.json`)

  console.log()
  console.log(`  ${chalk.bold.white('linklab docs')}  ·  ${chalk.cyan(alias)}`)
  console.log()

  if (!fs.existsSync(compiledPath)) {
    console.log(
      `  ${chalk.red('✖')}  ${alias}.json introuvable — lance "linklab build ${alias}" d'abord`
    )
    process.exit(1)
  }

  const compiled = JSON.parse(fs.readFileSync(compiledPath, 'utf-8'))
  const schema = fs.existsSync(schemaPath) ? JSON.parse(fs.readFileSync(schemaPath, 'utf-8')) : null
  const dict = fs.existsSync(dictPath) ? JSON.parse(fs.readFileSync(dictPath, 'utf-8')) : null
  const ucOverrideContent = fs.existsSync(ucOverride)
    ? JSON.parse(fs.readFileSync(ucOverride, 'utf-8'))
    : []
  const useCases =
    ucOverrideContent.length > 1 // plus d'un = dev a vraiment rempli
      ? ucOverrideContent
      : fs.existsSync(ucGenPath)
        ? JSON.parse(fs.readFileSync(ucGenPath, 'utf-8'))
        : ucOverrideContent

  if (!fs.existsSync(docsDir)) fs.mkdirSync(docsDir, { recursive: true })

  const version = compiled.version ?? '?'
  const date = new Date().toISOString().slice(0, 10)
  const dictRoutes = dict?.routes ?? {}

  // ── Helper : label humain depuis le dictionnaire ──────────────────────────

  function humanLabel(route: any): string {
    const key =
      route.label && route.semantic
        ? `${route.from}→${route.to}[${route.label}]`
        : `${route.from}→${route.to}`
    return dictRoutes[key]?.label ?? route.label ?? `${route.from}→${route.to}`
  }

  // ── entities.md ────────────────────────────────────────────────────────────

  const entitiesPath = path.join(docsDir, 'entities.md')
  let md = `# Entities — ${alias}\n\n`
  md += `> Generated by \`linklab docs\` · ${date} · v${version}\n\n---\n\n`

  for (const node of compiled.nodes as any[]) {
    md += `## ${node.id}\n\n`
    const entity = schema?.entities?.find((e: any) => e.name === node.id)
    if (entity?.properties?.length) {
      md += `| Colonne | Type | PK | FK | Indexé |\n`
      md += `|---------|------|----|----|--------|\n`
      for (const prop of entity.properties) {
        const pk = prop.isPK ? '✓' : ''
        const fk = prop.isFK ? `→ ${prop.references?.table ?? '?'}` : ''
        const idx = prop.isIndexed ? '✓' : ''
        md += `| \`${prop.name}\` | ${prop.type} | ${pk} | ${fk} | ${idx} |\n`
      }
    } else if (node.columns?.length) {
      md += `| Colonne | Type |\n|---------|------|\n`
      for (const col of node.columns) {
        md += `| \`${col.name ?? col}\` | ${col.type ?? ''} |\n`
      }
    } else {
      md += `_Aucune information de colonnes._\n`
    }
    md += `\n`
  }

  fs.writeFileSync(entitiesPath, md)
  console.log(
    `  ${chalk.green('✔')}  docs/entities.md   ${chalk.dim(`(${compiled.nodes.length} entities)`)}`
  )

  // ── routes.md ──────────────────────────────────────────────────────────────

  const routesPath = path.join(docsDir, 'routes.md')
  const routes = compiled.routes as any[]
  const physical = routes.filter(r => !r.semantic && !r.virtual)
  const semantic = routes.filter(r => r.semantic && !r.composed)
  const composed = routes.filter(r => r.composed)
  const virtual_ = routes.filter(r => r.virtual)

  let rmd = `# Routes — ${alias}\n\n`
  rmd += `> Generated by \`linklab docs\` · ${date} · v${version}\n\n`
  rmd += `**${routes.length} routes** — `
  rmd += `${physical.length} physical · ${semantic.length} semantic · ${composed.length} composed`
  if (virtual_.length) rmd += ` · ${virtual_.length} virtual`
  rmd += `\n\n---\n\n`

  if (physical.length) {
    rmd += `## Physical Routes\n\n`
    rmd += `| From | To | Path | Joins | Weight |\n`
    rmd += `|------|----|------|-------|--------|\n`
    for (const r of physical) {
      const pathStr = r.primary.path.join(' → ')
      rmd += `| \`${r.from}\` | \`${r.to}\` | ${pathStr} | ${r.primary.joins} | ${Number(r.primary.weight).toFixed(2)} |\n`
    }
    rmd += `\n`
  }

  if (semantic.length) {
    rmd += `## Semantic Routes\n\n`
    rmd += `| From | To | Label | Human Label | Path | Condition |\n`
    rmd += `|------|----|-------|-------------|------|----------|\n`
    for (const r of semantic) {
      const pathStr = r.primary.path.join(' → ')
      const cond = r.primary.edges?.[0]?.condition
        ? JSON.stringify(r.primary.edges[0].condition)
        : ''
      const human = humanLabel(r)
      rmd += `| \`${r.from}\` | \`${r.to}\` | \`${r.label ?? ''}\` | ${human !== r.label ? human : '—'} | ${pathStr} | \`${cond}\` |\n`
    }
    rmd += `\n`
  }

  if (composed.length) {
    rmd += `## Composed Routes\n\n`
    rmd += `_Routes composées = enchaînement de deux routes sémantiques via un pivot._\n\n`
    rmd += `| From | To | Label | Human Label | Path | Weight |\n`
    rmd += `|------|----|-------|-------------|------|--------|\n`
    for (const r of composed) {
      const pathStr = r.primary.path.join(' → ')
      const human = humanLabel(r)
      rmd += `| \`${r.from}\` | \`${r.to}\` | \`${r.label ?? ''}\` | ${human !== r.label ? human : '—'} | ${pathStr} | ${Number(r.primary.weight).toFixed(2)} |\n`
    }
    rmd += `\n`
  }

  if (virtual_.length) {
    rmd += `## Virtual Routes\n\n`
    rmd += `_Routes virtuelles = déclarées dans \`${alias}.override.json\`, sans FK réelle._\n\n`
    rmd += `| From | To | Label | Via |\n`
    rmd += `|------|----|-------|-----|\n`
    for (const r of virtual_) {
      const via = r.primary?.path?.[1] ?? '—'
      rmd += `| \`${r.from}\` | \`${r.to}\` | \`${r.label ?? ''}\` | ${via} |\n`
    }
    rmd += `\n`
  }

  fs.writeFileSync(routesPath, rmd)
  console.log(`  ${chalk.green('✔')}  docs/routes.md     ${chalk.dim(`(${routes.length} routes)`)}`)

  // ── use-cases.md ──────────────────────────────────────────────────────────

  const ucPath = path.join(docsDir, 'use-cases.md')
  let umd = `# Use Cases — ${alias}\n\n`
  umd += `> Generated by \`linklab docs\` · ${date}\n\n`

  if (useCases.length) {
    // Grouper par type
    const byType = new Map<string, any[]>()
    for (const uc of useCases) {
      const t = uc.type ?? 'other'
      if (!byType.has(t)) byType.set(t, [])
      byType.get(t)!.push(uc)
    }

    for (const [type, ucs] of byType) {
      umd += `## ${type.charAt(0).toUpperCase() + type.slice(1)} (${ucs.length})\n\n`
      umd += `| From | To | Label | Description |\n`
      umd += `|------|----|-------|-------------|\n`
      for (const uc of ucs) {
        umd += `| \`${uc.from}\` | \`${uc.to}\` | ${uc.semantic ?? '—'} | ${uc.description ?? ''} |\n`
      }
      umd += `\n`
    }
  } else {
    umd += `_Aucun use case. Lance \`linklab generate ${alias}\`._\n`
  }

  fs.writeFileSync(ucPath, umd)
  console.log(
    `  ${chalk.green('✔')}  docs/use-cases.md  ${chalk.dim(`(${useCases.length} use cases)`)}`
  )

  console.log()
  console.log(`  ${chalk.dim(`→ ${path.relative(cwd, docsDir)}/`)}`)
  console.log()
}
